In [1]:
import pandas as pd

In [4]:
df = pd.read_parquet("https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet")
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46912 entries, 0 to 46911
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               46912 non-null  int32
 1   lpep_pickup_datetime   46912 non-null  datetime64[us]
 2   lpep_dropoff_datetime  46912 non-null  datetime64[us]
 3   store_and_fwd_flag     41343 non-null  object
 4   RatecodeID             41343 non-null  float64
 5   PULocationID           46912 non-null  int32
 6   DOLocationID           46912 non-null  int32
 7   passenger_count        41343 non-null  float64
 8   trip_distance          46912 non-null  float64
 9   fare_amount            46912 non-null  float64
 10  extra                  46912 non-null  float64
 11  mta_tax                46912 non-null  float64
 12  tip_amount             46912 non-null  float64
 13  tolls_amount           46912 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  46912 non-null  float64
 16  total_amount           46912 non-null  float64
 17  payment_type           41343 non-null  float64
 18  trip_type              41342 non-null  float64
 19  congestion_surcharge   41343 non-null  float64
 20  cbd_congestion_fee     46912 non-null  float64
dtypes: datetime64[us](2), float64(15), int32(3), object(1)
memory usage: 7.0+ MB

In [6]:
df.describe()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
count,46912.000000,46912,46912,41343.000000,46912.000000,46912.000000,41343.000000,46912.000000,46912.000000,46912.000000,46912.000000,46912.000000,46912.000000,0.0,46912.000000,46912.000000,41343.000000,41342.000000,41343.000000,46912.000000
mean,2.240621,2025-11-15 20:09:38.177417,2025-11-15 20:30:49.202123,1.245193,97.521849,143.066678,1.290666,27.581932,17.260303,0.796294,0.556329,2.629329,0.273442,NaN,0.930615,25.193228,1.246209,1.055416,0.884061,0.064893
min,1.000000,2025-10-26 20:23:16,2025-10-26 20:31:18,1.000000,1.000000,1.000000,0.000000,0.000000,-150.000000,-2.500000,-0.500000,-0.900000,0.000000,NaN,-1.000000,-151.000000,1.000000,1.000000,-2.750000,-0.750000
25%,2.000000,2025-11-08 13:15:22.250000,2025-11-08 13:33:41,1.000000,74.000000,75.000000,1.000000,1.280000,9.000000,0.000000,0.500000,0.000000,0.000000,NaN,1.000000,14.840000,1.000000,1.000000,0.000000,0.000000
50%,2.000000,2025-11-15 18:51:45,2025-11-15 19:08:39.500000,1.000000,75.000000,140.000000,1.000000,2.070000,13.500000,0.000000,0.500000,2.080000,0.000000,NaN,1.000000,20.300000,1.000000,1.000000,0.000000,0.000000
75%,2.000000,2025-11-22 17:53:09.250000,2025-11-22 18:13:35.500000,1.000000,116.000000,230.000000,1.000000,3.660000,19.800000,1.000000,0.500000,3.920000,0.000000,NaN,1.000000,29.620000,1.000000,1.000000,2.750000,0.000000
max,6.000000,2025-12-01 20:29:00,2025-12-01 20:44:42,99.000000,265.000000,265.000000,9.000000,172273.800000,990.000000,10.000000,1.500000,122.100000,108.000000,NaN,1.000000,991.000000,5.000000,2.000000,2.750000,0.750000
std,1.169630,NaN,NaN,1.062821,56.622102,77.362396,0.897942,1386.578884,17.284706,1.364010,0.319524,3.411468,1.512830,NaN,0.233187,19.312283,0.460969,0.228793,1.285098,0.211081

In [7]:
df_nov = df[df['lpep_pickup_datetime'].dt.month == 11]

In [8]:
df_nov.describe()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
count,46891.000000,46891,46891,41322.000000,46891.000000,46891.000000,41322.000000,46891.000000,46891.000000,46891.000000,46891.000000,46891.000000,46891.000000,0.0,46891.000000,46891.000000,41322.000000,41321.000000,41322.000000,46891.000000
mean,2.240728,2025-11-15 20:07:20.005118,2025-11-15 20:28:31.126677,1.245317,97.526945,143.044678,1.290814,27.592691,17.258748,0.796480,0.556354,2.629373,0.273564,NaN,0.930584,25.192764,1.246213,1.055444,0.883978,0.064906
min,1.000000,2025-11-01 00:00:13,2025-11-01 00:02:31,1.000000,1.000000,1.000000,0.000000,0.000000,-150.000000,-2.500000,-0.500000,-0.900000,0.000000,NaN,-1.000000,-151.000000,1.000000,1.000000,-2.750000,-0.750000
25%,2.000000,2025-11-08 13:17:39.500000,2025-11-08 13:34:47.500000,1.000000,74.000000,75.000000,1.000000,1.280000,9.000000,0.000000,0.500000,0.000000,0.000000,NaN,1.000000,14.810000,1.000000,1.000000,0.000000,0.000000
50%,2.000000,2025-11-15 18:50:56,2025-11-15 19:06:31,1.000000,75.000000,140.000000,1.000000,2.070000,13.500000,0.000000,0.500000,2.080000,0.000000,NaN,1.000000,20.290000,1.000000,1.000000,0.000000,0.000000
75%,2.000000,2025-11-22 17:46:27.500000,2025-11-22 18:02:58.500000,1.000000,116.000000,230.000000,1.000000,3.660000,19.800000,1.000000,0.500000,3.920000,0.000000,NaN,1.000000,29.620000,1.000000,1.000000,2.750000,0.000000
max,6.000000,2025-11-30 23:58:28,2025-12-01 16:24:53,99.000000,265.000000,265.000000,9.000000,172273.800000,990.000000,10.000000,1.500000,122.100000,108.000000,NaN,1.000000,991.000000,5.000000,2.000000,2.750000,0.750000
std,1.169881,NaN,NaN,1.063077,56.626956,77.356844,0.898147,1386.889249,17.286684,1.364248,0.319593,3.412007,1.513157,NaN,0.233235,19.315025,0.460986,0.228848,1.285066,0.211101

In [9]:
df_nov.shape

(46891, 21)

In [10]:
df_nov[df_nov['trip_distance']<=1].shape

(8007, 21)

In [11]:
df_long = df_nov[df_nov['trip_distance']<=100]

In [21]:
df_long[df_long['trip_distance']==df_long['trip_distance'].max()]

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,trip_time
18867,2,2025-11-14 15:36:27,2025-11-14 18:40:48,N,4.0,130,265,2.0,88.03,610.6,...,0.0,0.0,NaN,1.0,612.1,2.0,1.0,0.0,0.0,0 days 03:04:21

In [12]:
df_long.describe()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
count,46870.000000,46870,46870,41322.000000,46870.000000,46870.000000,41322.000000,46870.000000,46870.000000,46870.000000,46870.000000,46870.000000,46870.000000,0.0,46870.000000,46870.000000,41322.000000,41321.000000,41322.000000,46870.000000
mean,2.240836,2025-11-15 20:09:44.847450,2025-11-15 20:30:55.706443,1.245317,97.513185,143.047685,1.290814,3.221124,17.250577,0.796837,0.556390,2.629552,0.272900,NaN,0.930582,25.185314,1.246213,1.055444,0.883978,0.064871
min,1.000000,2025-11-01 00:00:13,2025-11-01 00:02:31,1.000000,1.000000,1.000000,0.000000,0.000000,-150.000000,-2.500000,-0.500000,-0.900000,0.000000,NaN,-1.000000,-151.000000,1.000000,1.000000,-2.750000,-0.750000
25%,2.000000,2025-11-08 13:20:13,2025-11-08 13:38:44.500000,1.000000,74.000000,75.000000,1.000000,1.280000,9.000000,0.000000,0.500000,0.000000,0.000000,NaN,1.000000,14.800000,1.000000,1.000000,0.000000,0.000000
50%,2.000000,2025-11-15 18:51:12,2025-11-15 19:07:13,1.000000,75.000000,140.000000,1.000000,2.070000,13.500000,0.000000,0.500000,2.080000,0.000000,NaN,1.000000,20.290000,1.000000,1.000000,0.000000,0.000000
75%,2.000000,2025-11-22 17:48:45.500000,2025-11-22 18:07:37,1.000000,116.000000,230.000000,1.000000,3.660000,19.800000,1.000000,0.500000,3.920000,0.000000,NaN,1.000000,29.620000,1.000000,1.000000,2.750000,0.000000
max,6.000000,2025-11-30 23:58:28,2025-12-01 16:24:53,99.000000,265.000000,265.000000,9.000000,88.030000,990.000000,10.000000,1.500000,122.100000,108.000000,NaN,1.000000,991.000000,5.000000,2.000000,2.750000,0.750000
std,1.170132,NaN,NaN,1.063077,56.610402,77.356529,0.898147,3.551187,17.279453,1.364450,0.319652,3.411924,1.510108,NaN,0.233247,19.307437,0.460986,0.228848,1.285066,0.211050

In [13]:
df_long['trip_time'] = df_long['lpep_dropoff_datetime'] - df_long['lpep_pickup_datetime']

/tmp/ipykernel_7737/3954151766.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_long['trip_time'] = df_long['lpep_dropoff_datetime'] - df_long['lpep_pickup_datetime']

In [14]:
df_long.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,trip_time
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0,0 days 00:06:51
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0,0 days 00:05:35
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0,0 days 00:12:10
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0,0 days 00:13:56
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0,0 days 00:15:50

In [22]:
df_long[df_long['trip_time']==df_long['trip_time'].max()]

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,trip_time
12219,2,2025-11-09 20:55:53,2025-11-10 20:53:43,N,1.0,7,129,1.0,2.89,46.4,...,0.0,0.0,NaN,1.0,48.9,2.0,1.0,0.0,0.0,0 days 23:57:50

In [23]:
zone = pd.read_csv("https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv")

In [24]:
zone.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [25]:
df = pd.merge(df, zone, how="inner", right_on='LocationID', left_on='PULocationID')
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,LocationID,Borough,Zone,service_zone
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,1.0,11.64,1.0,1.0,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,1.0,9.70,2.0,1.0,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,1.0,21.00,1.0,1.0,0.00,0.0,83,Queens,Elmhurst/Maspeth,Boro Zone
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,1.0,27.70,1.0,1.0,0.00,0.0,166,Manhattan,Morningside Heights,Boro Zone
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.0,24.65,1.0,1.0,2.75,0.0,166,Manhattan,Morningside Heights,Boro Zone

In [26]:
df_nov18 = df[(df['lpep_pickup_datetime'].dt.month == 11) & (df['lpep_pickup_datetime'].dt.day == 18)]

In [27]:
df_nov18.shape

(1773, 25)

In [33]:
df_nov18.groupby('Zone').agg({"total_amount": "sum"}).reset_index().sort_values(by="total_amount", ascending=False)

                         Zone  total_amount
39          East Harlem North       9281.92
40          East Harlem South       6696.13
23               Central Park       2378.79
128  Washington Heights South       2139.05
85        Morningside Heights       2100.59
..                        ...           ...
125     Upper West Side South         16.00
124     Upper West Side North         16.00
129              West Village         16.00
12                  Bronxdale         13.57
14         Brooklyn Navy Yard          0.00

[136 rows x 2 columns]

In [35]:
df['drop_zone'] = df.set_index(["DOLocationID"]).map(zone.set_index(["LocationID"])['Zone'])

TypeError: the first argument must be callable